name: CI
on:
    push:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Purge Workflow History
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
      - name: Initialization
        continue-on-error: true
        run: |
          git config --global user.name "GHGaaa"
          git config --global user.email ${{ secrets.MAIL }}
          git config --global credential.helper store
          echo "https://GHGaaa:${{ secrets.G_TOKEN }}@github.com" > ~/.git-credentials
        shell: bash
      - name: F
        uses: P3TERX/ssh2actions@main
        timeout-minutes: 340
        continue-on-error: true
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      - name: Prepare for next run
        run: |
          git clone --depth=1 https://github.com/GHGaaa/Debug loop
          cd loop && sed -i "16s/Last Workflow Run-.*-informational.svg/Last Workflow Run-$(TZ='${{ secrets.TZ }}' date)-informational.svg/" README.md
          git add README.md && git commit --amend -m "$(curl -s http://whatthecommit.com/index.txt)"
          git push --force https://${{ secrets.G_TOKEN }}@github.com/GHGaaa/Debug HEAD:main
        shell: bash
